@TimeAdder.Api_HostAddress = http://localhost:5054

POST {{TimeAdder.Api_HostAddress}}/Time/
Accept: application/json
Content-Type: application/json
{
  "jobId": 1,
  "date": "2025-04-09",
  "time": "11:25"
}
###
